- .gitignore
- CMakeLists.txt
- cmake/modules/EnableCoverageReport.cmake
- cmake/modules/FindGtest.cmake
- cmake/modules/FindLcov.cmake
- cmake/modules/Findgcovr.cmake
- cmake/modules/ParseArguments.cmake
- src/CMakeLists.txt
- src/public/CMakeLists.txt
- src/public/cli/CMakeLists.txt
- src/public/cli/app/CMakeLists.txt
- src/public/cli/app/main.cpp
- tests/CMakeLists.txt
- tests/public/CMakeLists.txt
- tests/public/cli/CMakeLists.txt
- tests/public/cli/base_testcase.cpp
- tests/public/cli/base_testcase.h
- tests/public/cli/test_example.cpp
- tests/public/cli/test_example.h
Initialize the project so that it compiles a small app.
> Init the project.

- CMakeLists.txt
- src/priv/CMakeLists.txt
- src/priv/com/chancho/book.cpp
- src/priv/com/chancho/book.h
- src/priv/com/chancho/category.cpp
- src/priv/com/chancho/category.h
- src/priv/com/chancho/static_init.h
- src/priv/com/chancho/system/database.h
- src/priv/com/chancho/system/database_factory.cpp
- src/priv/com/chancho/system/database_factory.h
- src/priv/com/chancho/system/query.h
- src/public/cli/app/CMakeLists.txt
- tests/common/CMakeLists.txt
- tests/common/base_testcase.h
- tests/common/database.h
- tests/common/database_factory.h
- tests/common/matchers.h
- tests/common/public_book.h
- tests/common/public_category.h
- tests/common/query.h
- tests/priv/CMakeLists.txt
- tests/priv/test_book.cpp
- tests/priv/test_book.h
- tests/priv/test_book_category.cpp
- tests/priv/test_book_category.h
- tests/priv/test_book_mocked.cpp
- tests/priv/test_book_mocked.h
- tests/priv/test_category.cpp
Add sqlite support to store the diff categories in the application.
> Add support to the storage of categories in an application sqlite db.

- .travis.yml
- src/priv/CMakeLists.txt
- src/priv/com/chancho/account.cpp
- src/priv/com/chancho/account.h
- tests/priv/CMakeLists.txt
- tests/priv/test_account.cpp
- tests/priv/test_account.h
Start adding the representation of accounts in the system.
> Added account object.

- src/priv/com/chancho/account.cpp
- src/priv/com/chancho/account.h
- src/priv/com/chancho/book.cpp
- src/priv/com/chancho/book.h
- tests/common/CMakeLists.txt
- tests/common/public_account.h
- tests/priv/CMakeLists.txt
- tests/priv/test_account.cpp
- tests/priv/test_account.h
- tests/priv/test_book.cpp
- tests/priv/test_book_account.cpp
- tests/priv/test_book_account.h
- tests/priv/test_book_mocked.cpp
The accounts can now be stored in the local database.
> Added support for the accounts in the db.

- src/priv/CMakeLists.txt
- src/priv/com/chancho/transaction.cpp
- src/priv/com/chancho/transaction.h
- tests/common/CMakeLists.txt
- tests/common/public_transaction.h
- tests/priv/CMakeLists.txt
- tests/priv/test_category.cpp
- tests/priv/test_transaction.cpp
- tests/priv/test_transaction.h
Add an object that represents a transaction in an account.
> Added a transaction obj to store different operations.

- src/priv/com/chancho/book.cpp
- tests/priv/test_book_mocked.cpp
- tests/priv/test_book_transaction.cpp
- tests/priv/test_book_transaction.h
.Add an extra trigger that will ensure that moving transactions between accounts does update accounts accordinly fixing #14
> Ensure that accounts are correctly updated

- src/public/gui/app/qml/components/TransactionForm.qml
Set a min date for the picker.
> Fix issue #12 by setting the min date.

- src/public/gui/app/qml/components/EditAccount.qml
The ui will stop the user from deleting the last account by showing an error dialog.
> Stop the removal of the last account following #18.

- src/priv/com/chancho/stats.cpp
- src/priv/com/chancho/stats.h
- src/public/gui/app/qml/components/CategoryForm.qml
- src/public/gui/app/qml/components/EditCategory.qml
- src/public/gui/app/qml/components/js/categories.js
- src/public/gui/lib/com/chancho/qml/book.cpp
- src/public/gui/lib/com/chancho/qml/book.h
Adds a bar graph to the category page.
> Added a new graph that shows the category usage per month.

- src/priv/com/chancho/stats.cpp
- src/priv/com/chancho/stats.h
- src/public/gui/app/qml/components/AccountForm.qml
- src/public/gui/app/qml/components/CategoryForm.qml
- src/public/gui/app/qml/components/EditCategory.qml
- src/public/gui/app/qml/components/js/categories.js
- src/public/gui/lib/com/chancho/qml/book.cpp
- src/public/gui/lib/com/chancho/qml/book.h
Fix issue #33 by forcing a repaint.
> Update account graph

- src/public/gui/app/qml/components/EditCategory.qml
> Do not close the dialog in the callback the dialog already does it and

- src/public/gui/app/qml/components/TransactionComponent.qml
Fix some bugs in the transaction labels.
> Transaction labels

- src/public/gui/app/po/chancho.mandel.pot
- src/public/gui/app/qml/components/ColorChooser.qml
- src/public/gui/app/qml/components/WizardAccountsPage.qml
- src/public/gui/app/qml/components/WizardCategoriesPage.qml
- src/public/gui/app/qml/components/dialogs/ConfirmationDialog.qml
- src/public/gui/app/qml/components/dialogs/WizardNewAccountDialog.qml
- src/public/gui/app/qml/components/dialogs/WizardNewCategoryDialog.qml
> Rearrange the buttons to follow the ubuntu design guidelines

- src/public/gui/app/po/ro.po
Add the full Romanian translation.
> Update ro.po (POEditor.com)

- src/public/gui/app/po/el.po
- src/public/gui/app/po/it.po
Updated sentence in italian and added full greek translations.
> Updated languages

- .travis.yml
- src/public/gui/app/po/chancho.mandel.pot
- src/public/gui/app/qml/components/WizardCategoriesPage.qml
- src/public/gui/app/qml/components/dialogs/WizardNewCategoryDialog.qml
- src/public/gui/app/qml/components/js/categories_wizard.js
Ensures that a user cannot delete all categories in the wizard and also allows the user to choose the category type when adding a new category.
> Fix issue #124

- CMakeLists.txt
- src/public/gui/app/qml/components/SplashScreen.qml
The column does not have the right size, we need to use the parent. Fixes #127
> Ensure that the progressbar has the correct size

- src/priv/com/chancho/book.cpp
- src/priv/com/chancho/book.h
- src/public/gui/app/po/chancho.mandel.pot
- src/public/gui/lib/CMakeLists.txt
- src/public/gui/lib/com/chancho/qml/models/recurrent_transactions.cpp
- src/public/gui/lib/com/chancho/qml/models/recurrent_transactions.h
- src/public/gui/lib/com/chancho/qml/recurrent_transaction.h
- tests/common/book.h
- tests/priv/test_book_recurrent_transaction.cpp
- tests/priv/test_book_recurrent_transaction.h
- tests/public/gui/lib/CMakeLists.txt
- tests/public/gui/lib/public_recurrent_transactions_model.h
- tests/public/gui/lib/test_recurrent_transactions_model.cpp
- tests/public/gui/lib/test_recurrent_transactions_model.h
Added a model that allows to access the recurrent transactions.
> Add a model for recurrent transactions

- src/public/gui/app/po/de.po
better german translations. with comments for other possible translations and reasons for some of them.
> updates to german translations

- src/public/gui/app/CMakeLists.txt
- src/public/gui/app/po/chancho.mandel.pot
- src/public/gui/app/qml/components/recurrent_transactions/GeneratedTransactionsPage.qml
- src/public/gui/app/qml/components/recurrent_transactions/UpdateConfirmationDialog.qml
- src/public/gui/app/qml/components/transactions/Edit.qml
- src/public/gui/app/ui.qrc
- src/public/gui/lib/CMakeLists.txt
- src/public/gui/lib/com/chancho/qml/book.cpp
- src/public/gui/lib/com/chancho/qml/book.h
- src/public/gui/lib/com/chancho/qml/models/recurrent_categories.cpp
- src/public/gui/lib/com/chancho/qml/recurrent_transaction.h
- src/public/gui/lib/com/chancho/qml/workers/transactions.cpp
- src/public/gui/lib/com/chancho/qml/workers/transactions.h
- src/public/gui/lib/com/chancho/qml/workers/transactions/single_recurrent_update.cpp
- src/public/gui/lib/com/chancho/qml/workers/transactions/single_recurrent_update.h
- src/public/gui/lib/com/chancho/qml/workers/transactions/single_store.cpp
This code allow to edit the recurrent transactions and ensure that all or future transactions are updated.
> Add the required ui elements to allow users edit recurrent transactions.

- src/priv/com/chancho/book.cpp
- src/priv/com/chancho/book.h
- src/priv/com/chancho/recurrent_transaction.h
- src/public/gui/app/CMakeLists.txt
- src/public/gui/app/po/chancho.mandel.pot
- src/public/gui/app/qml/components/recurrent_transactions/GeneratedTransactionsPage.qml
- src/public/gui/app/qml/components/recurrent_transactions/RemoveConfirmationDialog.qml
- src/public/gui/app/ui.qrc
- src/public/gui/lib/CMakeLists.txt
- src/public/gui/lib/com/chancho/qml/book.cpp
- src/public/gui/lib/com/chancho/qml/book.h
- src/public/gui/lib/com/chancho/qml/models/recurrent_categories.cpp
- src/public/gui/lib/com/chancho/qml/workers/transactions.cpp
- src/public/gui/lib/com/chancho/qml/workers/transactions.h
- src/public/gui/lib/com/chancho/qml/workers/transactions/single_recurrent_remove.cpp
- src/public/gui/lib/com/chancho/qml/workers/transactions/single_recurrent_remove.h
- tests/common/book.h
- tests/common/matchers.h
- tests/priv/test_book_recurrent_transaction.cpp
- tests/priv/test_book_recurrent_transaction.h
- tests/public/gui/lib/workers/transactions/CMakeLists.txt
- tests/public/gui/lib/workers/transactions/test_single_recurrent_remove.cpp
- tests/public/gui/lib/workers/transactions/test_single_recurrent_remove.h
- tests/public/gui/lib/workers/transactions/test_single_recurrent_update.cpp
- tests/public/gui/lib/workers/transactions/test_single_recurrent_update.h
- tests/public/gui/lib/workers/transactions/test_single_store.cpp
Fix issue #169 by allowing the user to edit and remove recurrent transactions.
> Recurrent delete generated ui

- src/public/gui/app/po/chancho.mandel.pot
- src/public/gui/app/qml/components/recurrent_transactions/GeneratedTransactionsPage.qml
- src/public/gui/app/qml/components/recurrent_transactions/Page.qml
- src/public/gui/app/qml/components/transactions/Form.qml
- src/public/gui/lib/com/chancho/qml/models/generated_transactions.cpp
The flickables did not work very well, this branch improves the usage on the desktop.
> Improve the usage of the flickable panels on the desktop.

- CMakeLists.txt
- debian/changelog
Bump the version number to do a new release.
> Bump version number.
